version: '3.9'
services:
  api:
    build: ./server
    container_name: ilovexlsx-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  web:
    build: ./client
    container_name: ilovexlsx-web
    depends_on:
      api:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_BASE=http://api:8000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped

# Usage:
# docker compose build
# docker compose up -d
